name: Publish Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    env:
      COMPARISON_BRANCH: ${{ (github.event_name == 'pull_request' || github.event_name == 'pull_request_review') && github.event.pull_request.base.sha || github.event.before }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.6

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Create .npmrc
        run: |
          echo "@nayya-com:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Check package changes and changesets
        id: check-package-changes
        run: |
          # Get all package names from the packages directory
          packages=()

            # Find all package.json files within the packages directory
            for package_json in $(find packages -name "package.json"); do
              # Extract the name field from package.json using grep and sed
              name=$(grep -o '"name": *"@nayya-com[^"]*"' "$package_json" | sed 's/"name": *"//; s/"//')

              # Check if a name was found and add it to the array if it starts with "@nayya-com"
              if [[ $name == @nayya-com* ]]; then
                packages+=("$name")
              fi
            done

          # Loop through each package
          for package_name in "${packages[@]}"; do
            echo "Checking package: $package_name"
            changed=$(bash .github/check-package-changed.sh "$package_name" ${{ env.COMPARISON_BRANCH }})
            
            if [ "$changed" = "true" ]; then
              output=$(pnpm changeset status)
              if echo "$output" | grep -q "$package_name"; then
                echo "Found $package_name in changesets"
              else
                echo "No changes found for $package_name in changesets, but the package has changed or global files have changed. Please make a changeset for it."
                exit 1
              fi
            fi
          done

      - name: Commit version updates and publish to github packages
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Update versions and changelogs
          pnpm changeset version

          # Configure Git user
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Commit version updates
          git add .
          git commit -m "chore: update versions and changelogs"
          git push

          # Publish packages
          pnpm publish-packages
